apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: ops-platform
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: postgresql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque

  data:
    - secretKey: username
      remoteRef:
        key: 3rd-project/sandbox/postgresql
        property: username

    - secretKey: password
      remoteRef:
        key: 3rd-project/sandbox/postgresql
        property: password

    - secretKey: database
      remoteRef:
        key: 3rd-project/sandbox/postgresql
        property: database

    - secretKey: port
      remoteRef:
        key: 3rd-project/sandbox/postgresql
        property: port
