apiVersion: v1
kind: Namespace
metadata:
  name: ops-platform
  labels:
    app.kubernetes.io/name: ops-platform
    app.kubernetes.io/part-of: 3rd-project
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.30
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.30
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.30
