[master]
k8s-master ansible_host=43.203.247.95

[worker]
k8s-worker-1 ansible_host=43.203.126.119
k8s-worker-2 ansible_host=52.79.95.211
k8s-worker-3 ansible_host=3.36.123.162

[k8s:children]
master
worker

[k8s:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
