---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes

  tasks:

    - name: Check if cluster already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: not kubeadm_init.stat.exists
