---
- name: Install Metrics Server
  hosts: master
  become: yes

  tasks:
    - name: Install Metrics Server
      command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Patch Metrics Server for kubelet insecure TLS
      command: >
        kubectl patch deployment metrics-server
        -n kube-system
        --type=json
        -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      ignore_errors: yes
