name: Infra CI

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - "terraform-security/**"
      - "ansible/**"
      - ".github/workflows/infra-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - "terraform-security/**"
      - "ansible/**"
      - ".github/workflows/infra-ci.yml"

permissions:
  contents: read

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init without backend
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

  terraform-security-validate:
    name: Terraform Security Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-security

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init without backend
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

  ansible-syntax-check:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check Ansible version
        run: ansible --version

      - name: Ansible syntax check
        run: ansible-playbook -i inventory.ini site.yml --syntax-check
